name: build-index
on:
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # The "build" workflow
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install jq
      run: 'sudo apt-get install jq'
    - name: Compile Introduction Index
      run: '.github/workflows/build_index.sh'
    - name: Set up Cloud SDK
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: Upload Indexes
      uses: 'google-github-actions/upload-cloud-storage@v0.10.2'
      with:
        path: build
        destination: 'intronyc'

